### ISSUE TITLE
Should kinematics have current position?

### ISSUE THREAD

**Issue by Koeng101** [Koeng101/kinematics#5]
https://github.com/Koeng101/kinematics/blob/0ee00f99d8bb85c8c3188f9324343dd9f0dca604/kinematics.go#L131-L132

Should the kinematics have current position instead of a theta init of 0,0,0,0,0,0? Adding current position complicates the API, but may be more efficient when it comes to the amount that the joints have to move. We would like to build tests to test if it would be more efficient. If the tradeoff in complexity is worth it, we should add this in.

**Comment by maxschommer** [comment]
Yes, we almost definitely need the current position as input to IK. I'll work on a PR for this.

**Comment by Koeng101** [comment]
Why?

**Comment by maxschommer** [comment]
Each end effector pose has 8 solutions, and if we don't specify an initial set of joint angles, we could get any one of the 8 solutions depending on the path the optimizer took through joint space. This would result in a joint "flipping" randomly as the position changes, which would not be desirable.
